database:
  pool: 10
  connect_timeout: 15
  checkout_timeout: 15
  statement_timeout: 15s

domains:
  backoffice: backoffice
  app: app

default_url_options:
  protocol: http
  host: localhost
  port: 3000
