# Monit configuration for Puma
# Service name: puma_template-api-rails-app_production
#
check process puma_template-api-rails-app_production
  with pidfile "/home/deploy/apps/template-api-rails-app/production/shared/tmp/pids/puma.pid"
  start program = "/bin/systemctl --user start puma_template-api-rails-app_production"
  stop program = "/bin/systemctl --user stop puma_template-api-rails-app_production"
